---
title: "Publication ready plots"
project: "Vocatives"
author: "Marton Soskuthy & Timo Roettger"
date: "7/24/2019"
contacts: "timo.b.roettger@gmail.com, marton.soskuthy@ubc.ca"
output: html_document
---

```{r setup, include=FALSE}

knitr::opts_chunk$set(echo = TRUE)

```

## Prep

Loading libraries & raw data.

```{r preprocess}

# load packages
library(tidyverse)
library(ggbeeswarm)
library(brms)

# load data
v <- read_csv('../derived_data/vocatives_processed.csv')
langs <- read_csv('../derived_data/voc_languages.csv')

# join them
v <- full_join(v,langs)

# color scheme

# purple - green
#color1 = "#af8dc3"
#color2 = "#7fbf7b"

# red - blue
color1 = "#0571b0"
color2 = "#ca0020"
  
  
# store theme
theme_voc <- 
theme_classic() + 
  theme(legend.position = "none",
        legend.key.height = unit(2,"line"),
        legend.title = element_blank(),
        legend.text = element_text(size = 12),
        legend.background = element_rect(fill = "transparent"),
        strip.background = element_blank(),
        strip.text = element_text(size = 12, face = "bold"),
        panel.spacing = unit(2, "lines"),
        panel.border = element_blank(),
        plot.background = element_rect(fill = "transparent", colour = NA),
        panel.background = element_rect(fill = "transparent"),
        strip.text.y = element_text(size = 12, hjust = 0),
        axis.text = element_text(size = 12),
        axis.line = element_blank(),
        axis.ticks.x = element_blank(),
        axis.title = element_text(size = 12, face = "bold"),
        plot.title = element_text(size = 14, face = "bold"),
        plot.margin = unit(c(0.4,0.4,0.4,0.4),"cm"))


```
```{r agg}

# aggregate raw data over lang family
v_aggr <- v %>%
    filter(case_broad != "nom-like") %>% 
    dplyr::select(language, case_broad, prosody_clean,
         vowel_pres, cons_pres, cons_end, vowel_end, 
         obstr_vl_pres, v_long, family1, latitude, longitude) %>% 
  group_by(language, case_broad, family1) %>%
  summarise(vowel_pres = mean(vowel_pres, na.rm = T),
            cons_pres = mean(cons_pres, na.rm = T),
            vowel_end = mean(vowel_end, na.rm = T),
            obstr_vl_pres = mean(obstr_vl_pres, na.rm = T),
            v_long = mean(v_long, na.rm = T),
            cons_end = mean(cons_end, na.rm = T),
            prosody_clean = mean(prosody_clean, na.rm = T),
            latitude = mean(latitude),
            longitude = mean(longitude)) %>%
  ungroup()

# aggregated over families
v_aggr_family <- v_aggr %>%
  group_by(family1, case_broad) %>%
  add_tally() %>% 
  filter(!is.na(case_broad)) %>% 
  summarise(vowel_pres = mean(vowel_pres, na.rm = T),
            cons_pres = mean(cons_pres, na.rm = T),
            vowel_end = mean(vowel_end, na.rm = T),
            obstr_vl_pres = mean(obstr_vl_pres, na.rm = T),
            v_long = mean(v_long, na.rm = T),
            cons_end = mean(cons_end, na.rm = T),
            prosody_clean = mean(prosody_clean, na.rm = T),
            n = mean(n)) %>%
  ungroup()

# aggregate raw data over lang family and suffix vs. non-suffix
v_aggr_suffix <- v %>%
    filter(case_broad != "nom-like") %>% 
    filter(!is.na(form_add_suffix), 
           morphological == "affix") %>% 
    dplyr::select(language, case_broad, prosody_clean,
         vowel_pres, cons_pres, cons_end, vowel_end, 
         obstr_vl_pres, v_long, family1, latitude, longitude) %>% 
  group_by(language, case_broad, family1) %>%
  summarise(vowel_pres = mean(vowel_pres, na.rm = T),
            cons_pres = mean(cons_pres, na.rm = T),
            vowel_end = mean(vowel_end, na.rm = T),
            obstr_vl_pres = mean(obstr_vl_pres, na.rm = T),
            v_long = mean(v_long, na.rm = T),
            cons_end = mean(cons_end, na.rm = T),
            prosody_clean = mean(prosody_clean, na.rm = T),
            latitude = mean(latitude),
            longitude = mean(longitude)) %>%
  ungroup()


# aggregated over families
v_aggr_family_suffix <- v_aggr_suffix %>%
  group_by(family1, case_broad) %>%
  add_tally() %>% 
  filter(!is.na(case_broad)) %>% 
  summarise(vowel_pres = mean(vowel_pres, na.rm = T),
            cons_pres = mean(cons_pres, na.rm = T),
            vowel_end = mean(vowel_end, na.rm = T),
            obstr_vl_pres = mean(obstr_vl_pres, na.rm = T),
            v_long = mean(v_long, na.rm = T),
            cons_end = mean(cons_end, na.rm = T),
            prosody_clean = mean(prosody_clean, na.rm = T),
            n = mean(n)) %>%
  ungroup()


v_aggr$case_broad <- as.factor(v_aggr$case_broad)
levels(v_aggr$case_broad) <- c("accusative-like", "vocative")

v_aggr_family$case_broad <- as.factor(v_aggr_family$case_broad)
levels(v_aggr_family$case_broad) <- c("accusative-like", "vocative")

v_aggr_suffix$case_broad <- as.factor(v_aggr_suffix$case_broad)
levels(v_aggr_suffix$case_broad) <- c("accusative-like", "vocative")

v_aggr_family_suffix$case_broad <- as.factor(v_aggr_family_suffix$case_broad)
levels(v_aggr_family_suffix$case_broad) <- c("accusative-like", "vocative")


v_acc_voc <- v %>%
  filter(case_broad != "nom-like") %>% 
  mutate(case_broad_sum=ifelse(case_broad=="vocative", 1, 0),
         case_broad_sum=case_broad_sum-mean(case_broad_sum))

```


## Consonants presence

### Prepare

```{r prep consonants}

# load in model output for overall consonant model
cons_pres_model <- readRDS('../models/mod_consonants.rds')

# extract posteriors
mod_cons_pres_strict_psamp <- as.matrix(posterior_samples(cons_pres_model)[,1:2])

# accusative-like - all probabilities
mod_cons_pres_strict_acc_probs <- plogis(mod_cons_pres_strict_psamp %*% matrix(c(1, min(v_acc_voc$case_broad_sum))))

# get posterior mean and 95% CI for accusative
mean <- round(mean(mod_cons_pres_strict_acc_probs), 5)
lower <- round(quantile(mod_cons_pres_strict_acc_probs, 0.025), 5)
upper <- round(quantile(mod_cons_pres_strict_acc_probs, 0.975), 5)

cons_pres_acc_post <- data.frame(mean, lower, upper, row.names = NULL)

# vocative-like - all probabilities
mod_cons_pres_strict_voc_probs <- plogis(mod_cons_pres_strict_psamp %*% matrix(c(1, max(v_acc_voc$case_broad_sum))))

# get posterior mean and 95% CI for accusative
mean <- round(mean(mod_cons_pres_strict_voc_probs), 5)
lower <- round(quantile(mod_cons_pres_strict_voc_probs, 0.025), 5)
upper <- round(quantile(mod_cons_pres_strict_voc_probs, 0.975), 5)

cons_pres_voc_post <- data.frame(mean, lower, upper, row.names = NULL)

# merge
cons_pres_post <- rbind(cons_pres_acc_post, cons_pres_voc_post)
cons_pres_post$case_broad <- c("accusative-like", "vocative")

#####

# load in model output for presence of consonants only in suffixes
cons_pres_suff_model <- readRDS('../models/mod_consonants_suff.rds')

# extract posteriors
mod_cons_pres_suff_strict_psamp <- as.matrix(posterior_samples(cons_pres_suff_model)[,1:2])

# accusative-like - all probabilities
mod_cons_pres_suff_strict_acc_probs <- plogis(mod_cons_pres_suff_strict_psamp %*% matrix(c(1, min(v_acc_voc$case_broad_sum))))

# get posterior mean and 95% CI for accusative
mean <- round(mean(mod_cons_pres_suff_strict_acc_probs), 5)
lower <- round(quantile(mod_cons_pres_suff_strict_acc_probs, 0.025), 5)
upper <- round(quantile(mod_cons_pres_suff_strict_acc_probs, 0.975), 5)

cons_pres_suff_acc_post <- data.frame(mean, lower, upper, row.names = NULL)

# vocative-like - all probabilities
mod_cons_pres_suff_strict_voc_probs <- plogis(mod_cons_pres_suff_strict_psamp %*% matrix(c(1, max(v_acc_voc$case_broad_sum))))

# get posterior mean and 95% CI for accusative
mean <- round(mean(mod_cons_pres_suff_strict_voc_probs), 5)
lower <- round(quantile(mod_cons_pres_suff_strict_voc_probs, 0.025), 5)
upper <- round(quantile(mod_cons_pres_suff_strict_voc_probs, 0.975), 5)

cons_pres_suff_voc_post <- data.frame(mean, lower, upper, row.names = NULL)

# merge
cons_pres_suff_post <- rbind(cons_pres_suff_acc_post, cons_pres_suff_voc_post)
cons_pres_suff_post$case_broad <- c("accusative-like", "vocative")    
  

```

### Plot overall pattern

```{r plot consonant presence}

# plot and save
ggplot(data = cons_pres_post, aes(x = case_broad, y = mean)) +
  geom_point(data = v_aggr_family, aes(x = case_broad, y = cons_pres, 
                                       fill = cons_pres, 
                                       size = n), 
             alpha = 0.6, shape = 21, color = "black", stroke = 0.1,
             position = position_quasirandom(width = 0.2)) +
  #geom_line(aes( group = 1)) +
  geom_errorbar(aes(ymin = lower, ymax = upper), 
                width = 0.075) +
  geom_point(aes(fill = mean), shape = 21, stroke = 1, size = 6) +
  #scale_shape_manual(values = c(24,25)) +
  scale_fill_gradient2(limits = c(0,1), breaks = c(0,0.25,0.5,0.75,1),
                      low = color1, midpoint = 0.5, high = color2) +
  scale_color_gradient2(limits = c(0,1), breaks = c(0,0.25,0.5,0.75,1),
                       low = color1, midpoint = 0.5, high = color2) +
  scale_size_continuous(guide = FALSE, range = c(2,6)) +
  labs(title = "Results: Presence of consonant",
       subtitle = "Overall: Vocatives often have no consonants\n",
       y = "proportion of forms \nwith a consonant\n", 
       x = "\n") +
  theme_voc

# save  
#ggsave("../plots/consonant.pdf", width = 5.5, height = 3.6)
#ggsave("../plots/consonant.png", width = 5.5, height = 3.6)


```

## Plot maps of the major finding

### Consonants

```{r map plots}
default_classes <- c("m","[-f]","m-I", "class I", "declension I", "animate", "classes I, II, III", "masculine")
set.seed(1)
v_map <- filter(v, form_add != "zero") %>%
  group_by(language, case_broad) %>%
  # if there's a default, keep that, discard everything else
  mutate(default.exists=sum(default) > 0) %>%
  filter((default.exists & default) | (!default.exists)) %>%
  dplyr::select(-default.exists) %>%
  # if there are singulars, keep those, discard everything else
  mutate(singular.exists=sum(number %in% c("sg", "singular")) > 0) %>%
  filter((singular.exists & number %in% c("sg", "singular")) | (!singular.exists)) %>%
  dplyr::select(-singular.exists) %>%
  # if there is an affix as opposed to a particle, keep that, discard everything else
  mutate(affix.exists=sum(morphological=="affix") > 0) %>%
  filter((affix.exists & morphological=="affix") | (!affix.exists)) %>%
  dplyr::select(-affix.exists) %>%
  # if there is a masculine / class I / declension I, keep that, discard everything else
  mutate(def.class.exists=sum(noun_class %in% default_classes) > 0) %>%
  filter((def.class.exists & noun_class %in% default_classes) | (!def.class.exists)) %>%
  dplyr::select(-def.class.exists) %>%
  # otherwise, randomly choose one
  mutate(random_keep_it=sample(c(rep(F, length(form_add)-1), T), length(form_add), replace=F)) %>%
  filter(random_keep_it) %>%
  dplyr::select(-random_keep_it) %>%
  # ungroup
  ungroup()

v_map_voc <- filter(v_map, case_broad=="vocative")
v_map_acc <- filter(v_map, case_broad=="acc-like")
library(maps)

### vocatives

world_map <- map_data("world")

map <- ggplot(world_map, aes(x = long, y = lat, group = group)) +
  geom_polygon(fill = "gray92", colour = "white", size = 0.2) +
  geom_text_repel(data = v_map_voc, aes(x = longitude, y = latitude, label = form_add, col = cons_pres, group = NA), size = 3.3, alpha = 0.8,
  segment.size=0, force=0.01, max.iter=5000, box.padding=0, point.padding=NA,
  fontface="bold") +
  coord_map(xlim = c(-180, 180),ylim = c(-60, 90)) +
  #coord_fixed(ylim = c(-60, 80), ratio = 1) +
  #ylim(-60,80) +
  #facet_grid(~case_broad) +
  #scale_shape_manual(guide = FALSE, values = c(24,25)) +
  scale_color_manual(values = c(color1, color2), guide=F) +
  #scale_fill_gradient2(limits = c(0,1), breaks = c(0,0.25,0.5,0.75,1),
  #                     low = color1, midpoint = 0.5, high = color2) +
  #labs(title = "Map: Presence of consonants in suffixes",
  #     subtitle = "Vocatives often have no consonants\n") +
  theme_voc +
  theme(
    legend.position = "right",
    axis.title = element_blank(),
    axis.text = element_blank(),
    axis.line = element_blank(),
    axis.ticks = element_blank())

cairo_pdf("../plots/labphon_vocatives.pdf", width = 10, height = 5)
map
dev.off()

# save  
# ggsave("../plots/labphon_vocatives.pdf", width = 10, height = 3.6)


### accusatives
map <- ggplot(world_map, aes(x = long, y = lat, group = group)) +
  geom_polygon(fill = "gray92", colour = "white", size = 0.2) +
  geom_text_repel(data = v_map_acc, aes(x = longitude, y = latitude, label = form_add, col = cons_pres, group = NA), size = 3.3, alpha = 0.8,
  segment.size=0, force=0.01, max.iter=5000, box.padding=0, point.padding=NA,
  fontface="bold") +
  coord_map(xlim = c(-180, 180),ylim = c(-60, 90)) +
  #coord_fixed(ylim = c(-60, 80), ratio = 1) +
  #ylim(-60,80) +
  #facet_grid(~case_broad) +
  #scale_shape_manual(guide = FALSE, values = c(24,25)) +
  scale_color_manual(values = c(color1, color2), guide=F) +
  #scale_fill_gradient2(limits = c(0,1), breaks = c(0,0.25,0.5,0.75,1),
  #                     low = color1, midpoint = 0.5, high = color2) +
  #labs(title = "Map: Presence of consonants in suffixes",
  #     subtitle = "Vocatives often have no consonants\n") +
  theme_voc +
  theme(
    legend.position = "right",
    axis.title = element_blank(),
    axis.text = element_blank(),
    axis.line = element_blank(),
    axis.ticks = element_blank())

cairo_pdf("../plots/labphon_accusatives.pdf", width = 10, height = 5)
map
dev.off()

# save  
# ggsave("../plots/labphon_accusatives.pdf", width = 10, height = 5)
```




